# Generated by Django 5.1.3 on 2024-11-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobiliare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(verbose_name=250),
        ),
    ]
