# Generated by Django 5.1.3 on 2024-11-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobiliare', '0003_agenti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenti',
            name='id',
        ),
        migrations.AlterField(
            model_name='agenti',
            name='cf',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
