# Generated by Django 5.1.3 on 2024-11-30 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobiliare', '0004_remove_agenti_id_alter_agenti_cf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appuntamenti',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_appuntamento', models.DateField()),
                ('cliente', models.CharField(max_length=255)),
                ('immobile', models.IntegerField()),
                ('ora_appuntamento', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Clienti',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=255)),
                ('telefono1', models.CharField(max_length=255, null=True)),
                ('telefono2', models.CharField(max_length=255, null=True)),
                ('ultimo_immobile_visto', models.IntegerField(null=True)),
                ('nome', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietari',
            fields=[
                ('cf', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('nome', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Immobili',
            fields=[
                ('riferimento', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('situazione', models.CharField(choices=[(1, 'In vendita'), (2, 'In affitto'), (3, 'Venduto'), (4, 'Affittato'), (5, 'Non disponibile')], default=1, max_length=100)),
                ('prezzo', models.IntegerField(max_length=11)),
                ('metratura', models.IntegerField(max_length=11)),
                ('stato', models.CharField(max_length=255)),
                ('citta', models.CharField(max_length=255)),
                ('via', models.CharField(max_length=255)),
                ('civico', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[(1, 'Casa indipendente'), (2, 'Appartamento'), (3, 'Rustico'), (4, 'Altro')], default=1, max_length=100)),
                ('descrizione', models.CharField(max_length=10000)),
                ('spese_amministrazione', models.FloatField()),
                ('spese_riscaldamento', models.FloatField()),
                ('foto', models.IntegerField(max_length=11)),
                ('video', models.IntegerField(max_length=11)),
                ('fasce_visite', models.CharField(max_length=255)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immobiliare.agenti')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immobiliare.proprietari')),
            ],
        ),
    ]
