# Generated by Django 5.1.3 on 2024-11-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobiliare', '0005_appuntamenti_clienti_proprietari_immobili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobili',
            name='foto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='immobili',
            name='metratura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='immobili',
            name='prezzo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='immobili',
            name='riferimento',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='immobili',
            name='video',
            field=models.IntegerField(),
        ),
    ]
