# Generated by Django 5.1.3 on 2024-11-30 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobiliare', '0006_alter_immobili_foto_alter_immobili_metratura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobili',
            name='agente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='immobiliare.agenti'),
        ),
    ]
