# Generated by Django 5.1.3 on 2024-11-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immobiliare', '0008_alter_immobili_proprietario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenti',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='appuntamenti',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clienti',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='immobili',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='proprietari',
            options={'managed': False},
        ),
    ]
