# Generated by Django 5.1.3 on 2024-11-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immobiliare', '0009_alter_agenti_options_alter_appuntamenti_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agenti',
            table='immobiliare.agenti',
        ),
        migrations.AlterModelTable(
            name='appuntamenti',
            table='immobiliare.appuntamenti',
        ),
        migrations.AlterModelTable(
            name='clienti',
            table='immobiliare.clienti',
        ),
        migrations.AlterModelTable(
            name='immobili',
            table='immobiliare.immobili',
        ),
        migrations.AlterModelTable(
            name='proprietari',
            table='immobiliare.proprietari',
        ),
    ]
