# Generated by Django 5.1.3 on 2024-11-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immobiliare', '0010_alter_agenti_table_alter_appuntamenti_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agenti',
            table='agenti',
        ),
        migrations.AlterModelTable(
            name='appuntamenti',
            table='appuntamenti',
        ),
        migrations.AlterModelTable(
            name='clienti',
            table='clienti',
        ),
        migrations.AlterModelTable(
            name='immobili',
            table='immobili',
        ),
        migrations.AlterModelTable(
            name='proprietari',
            table='proprietari',
        ),
    ]
