# Generated by Django 5.1.3 on 2024-11-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immobiliare', '0011_alter_agenti_table_alter_appuntamenti_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenti',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='appuntamenti',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='clienti',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='immobili',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proprietari',
            options={'managed': True},
        ),
    ]
