# Generated by Django 5.1.3 on 2024-12-01 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobiliare', '0012_alter_agenti_options_alter_appuntamenti_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobili',
            name='agente',
            field=models.ForeignKey(db_column='agente', null=True, on_delete=django.db.models.deletion.CASCADE, to='immobiliare.agenti'),
        ),
    ]
