# Generated by Django 5.1.3 on 2024-12-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobiliare', '0014_alter_immobili_proprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobili',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='immobili/'),
        ),
    ]
