# Generated by Django 5.1.3 on 2024-12-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobiliare', '0016_alter_immobili_fasce_visite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobili',
            name='situazione',
            field=models.CharField(choices=[('In vendita', 'In vendita'), ('In affitto', 'In affitto'), ('Venduto', 'Venduto'), ('Affittato', 'Affittato'), ('Non disponibile', 'Non disponibile')], default='In vendita', max_length=100),
        ),
    ]
