# Generated by Django 5.1.3 on 2024-12-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobiliare', '0017_alter_immobili_situazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobili',
            name='fasce_visite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='immobili',
            name='tipo',
            field=models.CharField(choices=[('Casa indipendente', 'Casa indipendente'), ('Appartamento', 'Appartamento'), ('Rustico', 'Rustico'), ('Altro', 'Altro')], default='Casa indipendente', max_length=100),
        ),
        migrations.AlterField(
            model_name='immobili',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to='immobili/'),
        ),
    ]
