# Generated by Django 5.1.3 on 2024-12-01 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobiliare', '0019_delete_todoitem_alter_agenti_trattative_concluse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('file_path', models.URLField(max_length=255)),
                ('descrizione', models.CharField(blank=True, max_length=255, null=True)),
                ('immobile', models.ForeignKey(db_column='immobile', on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='immobiliare.immobili')),
            ],
        ),
    ]
